# Autor: Robson Vaamonde
# Script utilizado no Curso de OCS Inventory Server
# Site: www.procedimentosemti.com.br
# Facebook: facebook.com/ProcedimentosEmTI
# Facebook: facebook.com/BoraParaPratica
# YouTube: youtube.com/BoraParaPratica
# Data de criação: 31/05/2016
# Data de atualização: 04/01/2018
# Versão: 0.5
# Testado e homologado para a versão do Ubuntu Server 16.04 LTS x64
# Kernel >= 4.4.x

<IfModule mod_ssl.c>
	<VirtualHost _default_:443>
	
		#Configuração padrão, não alterar
		ServerAdmin pti@pti.intra
		DocumentRoot /var/www/html
		ErrorLog ${APACHE_LOG_DIR}/error.log
		CustomLog ${APACHE_LOG_DIR}/access.log combined
		SSLEngine on

		#Configuração dos certificados utilizado pelo OCS Inventory Reports
		SSLCertificateFile	/etc/ssl/certs/ocs.crt
		SSLCertificateKeyFile /etc/ssl/private/ocs.key

		#Configuração padrão, não alterar
		<FilesMatch "\.(cgi|shtml|phtml|php)$">
				SSLOptions +StdEnvVars
		</FilesMatch>
		<Directory /usr/lib/cgi-bin>
				SSLOptions +StdEnvVars
		</Directory>

		#Configuração do Alias da Pasta Download utilizado pelo OCS Inventory Reports
		Alias /download /var/lib/ocsinventory-reports/download
		<Directory /var/lib/ocsinventory-reports/download>
			Options Indexes FollowSymLinks MultiViews
			AllowOverride None
			Order allow,deny
			allow from all
		</Directory>
		
		#Configuração do Alias da Pasta SNMP utilizado pelo OCS Inventory Reports
		Alias /snmp /var/lib/ocsinventory-reports/snmp
		<Directory /var/lib/ocsinventory-reports/snmp>
			Options Indexes FollowSymLinks MultiViews
			AllowOverride None
			Order allow,deny
			allow from all
		</Directory>

	</VirtualHost>
</IfModule>

# vim: syntax=apache ts=4 sw=4 sts=4 sr noet
